{
 "title": "National Security Overview",
 "tags": [
  "observability",
  "critical"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active Services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traffic Distribution (Req/sec)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "{{job}} - {{code}}" }
   ]
  },
  {
   "title": "Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{job}} Latency"
    }
   ]
  }
 ]
}