# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import national_security_pb2 as national__security__pb2


class IntelligenceServiceStub(object):
    """Service Definition for the Python Intelligence Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeAlert = channel.unary_unary(
                '/national_security.IntelligenceService/AnalyzeAlert',
                request_serializer=national__security__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=national__security__pb2.AnalyzeResponse.FromString,
                )


class IntelligenceServiceServicer(object):
    """Service Definition for the Python Intelligence Service
    """

    def AnalyzeAlert(self, request, context):
        """Analyze an alert for severity, keywords, and translation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntelligenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeAlert,
                    request_deserializer=national__security__pb2.AnalyzeRequest.FromString,
                    response_serializer=national__security__pb2.AnalyzeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'national_security.IntelligenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IntelligenceService(object):
    """Service Definition for the Python Intelligence Service
    """

    @staticmethod
    def AnalyzeAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/national_security.IntelligenceService/AnalyzeAlert',
            national__security__pb2.AnalyzeRequest.SerializeToString,
            national__security__pb2.AnalyzeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class CoreServiceStub(object):
    """Service Definition for the Core API (Go)
    Mobile App will likely use HTTP/JSON, but Backend-to-Backend uses gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitAlert = channel.unary_unary(
                '/national_security.CoreService/SubmitAlert',
                request_serializer=national__security__pb2.Alert.SerializeToString,
                response_deserializer=national__security__pb2.SubmitAlertResponse.FromString,
                )


class CoreServiceServicer(object):
    """Service Definition for the Core API (Go)
    Mobile App will likely use HTTP/JSON, but Backend-to-Backend uses gRPC
    """

    def SubmitAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAlert,
                    request_deserializer=national__security__pb2.Alert.FromString,
                    response_serializer=national__security__pb2.SubmitAlertResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'national_security.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """Service Definition for the Core API (Go)
    Mobile App will likely use HTTP/JSON, but Backend-to-Backend uses gRPC
    """

    @staticmethod
    def SubmitAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/national_security.CoreService/SubmitAlert',
            national__security__pb2.Alert.SerializeToString,
            national__security__pb2.SubmitAlertResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
