// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: national_security.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IntelligenceServiceClient is the client API for IntelligenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntelligenceServiceClient interface {
	// Analyze an alert for severity, keywords, and translation
	AnalyzeAlert(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
}

type intelligenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntelligenceServiceClient(cc grpc.ClientConnInterface) IntelligenceServiceClient {
	return &intelligenceServiceClient{cc}
}

func (c *intelligenceServiceClient) AnalyzeAlert(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, "/national_security.IntelligenceService/AnalyzeAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntelligenceServiceServer is the server API for IntelligenceService service.
// All implementations must embed UnimplementedIntelligenceServiceServer
// for forward compatibility
type IntelligenceServiceServer interface {
	// Analyze an alert for severity, keywords, and translation
	AnalyzeAlert(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	mustEmbedUnimplementedIntelligenceServiceServer()
}

// UnimplementedIntelligenceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIntelligenceServiceServer struct {
}

func (UnimplementedIntelligenceServiceServer) AnalyzeAlert(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeAlert not implemented")
}
func (UnimplementedIntelligenceServiceServer) mustEmbedUnimplementedIntelligenceServiceServer() {}

// UnsafeIntelligenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntelligenceServiceServer will
// result in compilation errors.
type UnsafeIntelligenceServiceServer interface {
	mustEmbedUnimplementedIntelligenceServiceServer()
}

func RegisterIntelligenceServiceServer(s grpc.ServiceRegistrar, srv IntelligenceServiceServer) {
	s.RegisterService(&IntelligenceService_ServiceDesc, srv)
}

func _IntelligenceService_AnalyzeAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).AnalyzeAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/national_security.IntelligenceService/AnalyzeAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).AnalyzeAlert(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntelligenceService_ServiceDesc is the grpc.ServiceDesc for IntelligenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntelligenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "national_security.IntelligenceService",
	HandlerType: (*IntelligenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeAlert",
			Handler:    _IntelligenceService_AnalyzeAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "national_security.proto",
}

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreServiceClient interface {
	SubmitAlert(ctx context.Context, in *Alert, opts ...grpc.CallOption) (*SubmitAlertResponse, error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) SubmitAlert(ctx context.Context, in *Alert, opts ...grpc.CallOption) (*SubmitAlertResponse, error) {
	out := new(SubmitAlertResponse)
	err := c.cc.Invoke(ctx, "/national_security.CoreService/SubmitAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServiceServer is the server API for CoreService service.
// All implementations must embed UnimplementedCoreServiceServer
// for forward compatibility
type CoreServiceServer interface {
	SubmitAlert(context.Context, *Alert) (*SubmitAlertResponse, error)
	mustEmbedUnimplementedCoreServiceServer()
}

// UnimplementedCoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCoreServiceServer struct {
}

func (UnimplementedCoreServiceServer) SubmitAlert(context.Context, *Alert) (*SubmitAlertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAlert not implemented")
}
func (UnimplementedCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_SubmitAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Alert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SubmitAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/national_security.CoreService/SubmitAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SubmitAlert(ctx, req.(*Alert))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "national_security.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitAlert",
			Handler:    _CoreService_SubmitAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "national_security.proto",
}
